apiVersion: v1
kind: Pod
metadata:
  labels:
    run: metrics-generator
  name: metrics-generator
  annotation:
    prometheus.io/path: /metrics
    prometheus.io/port: 8080
    prometheus.io/scrape: "true"
spec:
  containers:
  - image: seongjumoon/metrics-generator
    name: metrics-generator
    ports:
    - containerPort: 8080